version: '3'

volumes:
  mongodb-db:
    driver: local

services:
  server:
    build: .
    environment:
      MONGO_CONN_STRING: "mongodb://mongo:27017/DB"
      PORT: "3000"
      GOOGLE_CLIENT_IDS: "CLIENT_ID;CLIENT_ID"
      JWT_SECRET : "JWT_SECRET"
      GOOGLE_APPLICATION_CREDENTIALS: "/lms/capstone.json" # credentials for accessing google bucket https://cloud.google.com/docs/authentication/production
    depends_on:
      - mongo
    ports:
      - 3000:3000
  notifications:
    build:
      context: .
      dockerfile: Dockerfile-notifications
    environment:
      MONGO_CONN_STRING: "mongodb://mongo:27017/DB"
      PORT: "3000"
      GOOGLE_CLIENT_IDS: "CLIENT_ID;CLIENT_ID"
      JWT_SECRET : "JWT_SECRET"
      GOOGLE_APPLICATION_CREDENTIALS: "/lms/capstone.json" # credentials for accessing google bucket https://cloud.google.com/docs/authentication/production
    depends_on:
      - mongo
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - mongodb-db:/data/db
    ports:
      - 27017:27017