version: '3'

volumes:
  mongodb:
    driver: local

services:
  node:
    build: .
    environment:
      MONGO_CONN_STRING: "mongodb://mongo:27017/DB"
      PORT: "3000"
    depends_on:
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - mongodb:/data/db