version: '3'

volumes:
  mongodb-db:
    driver: local

services:
  node:
    build: .
    environment:
      MONGO_CONN_STRING: "mongodb://mongo:27017/DB"
      PORT: "3000"
      GOOGLE_CLIENT_ID: "CLIENT_ID"
      JWT_SECRET : "JWT_SECRET"
    depends_on:
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - mongodb-db:/data/db
    ports:
      - 27017:27017