openapi: 3.0.0
info:
  title: Library System API
  version: 0.0.1
servers:
  - url: 'http://localhost:8080/'
    description: local
paths:
  /user/sessions:
    post:
      summary: signin endpoint for user
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['success']
                  response:
                    type: object
                    properties:
                      token:
                        type: string
                      refreshToken:
                        type: string
    delete:
      summary: signout endpoint for user
      tags:
        - users
      parameters:
        - in: query
          name: refreshToken
          schema:
            type: string
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['success']
                  response:
                    type: string
                    enum: ['User has signed out']
  /tokens:
    post:
      summary: endpoint for refreshing token
      tags:
        - tokens
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['success']
                  response:
                    type: object
                    properties:
                      token:
                        type: string
  /users/me:
    get:
      summary: "Endpoint for getting user info"
      tags:
        - users
      security:
        - KeyAuth: []
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['success']
                  response:
                    $ref: '#/components/schemas/User'
  /books/home:
    get:
      summary: "Home page endpoint for book"
      tags:
        - books
      security:
        - KeyAuth: []
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['success']
                  response:
                    type: object
                    properties:
                      latest_books:
                        type: array
                        items:
                          $ref: '#/components/schemas/Book'
                      most_favorite_books:
                        type: array
                        items:
                          $ref: '#/components/schemas/Book'
  /books/favorite:
    get:
      summary: "Favorite books endpoint for user"
      tags:
        - books
      security:
        - KeyAuth: [ ]
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ 'success' ]
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
                  metadata:
                    type: object
                    properties:
                      nextPage:
                        type: string
  /orders:
    get:
      summary: "Get orders of user"
      tags:
        - orders
      security:
        - KeyAuth: [ ]
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [ 'taken', 'returned' ]
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ 'success' ]
                  response:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/Order'
                        - type: object
                          properties:
                            book:
                              $ref: '#/components/schemas/Book'
                  metadata:
                    type: object
                    properties:
                      nextPage:
                        type: string
    post:
      summary: "Create order, when admin hands the book to a user (admin)"
      tags:
        - orders
      security:
        - KeyAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                book_id:
                  type: string
                return_date:
                  type: string
                  format: date
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ 'success' ]
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  metadata:
                    type: object
                    properties:
                      nextPage:
                        type: string
  /books/{id}:
    get:
      summary: "Get book by id"
      tags:
        - books
      security:
        - KeyAuth: [ ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ 'success' ]
                  response:
                    $ref: '#/components/schemas/Book'
    delete:
      summary: "Delete book by id (admin)"
      tags:
        - books
      security:
        - KeyAuth: [ ]
      parameters:
        - in: path
          required : true
          name: id
          schema:
            type: string
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ 'success' ]
                  response:
                    type: string
                    enum: [ 'Book deleted' ]
  /books:
    get:
      summary: "Browse books endpoint"
      tags:
        - books
      security:
        - KeyAuth: [ ]
      parameters:
        - in: query
          name: keywords
          schema:
            type: array
            items:
              type: string
        - in: query
          name: param
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ 'success' ]
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
    post:
      summary: "Create book (admin)"
      tags:
        - books
      security:
        - KeyAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookPayload'
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ 'success' ]
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'



components:
  securitySchemes:
    KeyAuth:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    Order:
      type: object
    Book:
      type: object
    BookPayload:
      type: object
    User:
      type: object